FROM golang:latest

RUN apt update && \
	apt upgrade -y && \
	apt install lsb-release -y

RUN curl -L https://packagecloud.io/golang-migrate/migrate/gpgkey | apt-key add - && \
	echo "deb https://packagecloud.io/golang-migrate/migrate/debian/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/migrate.list && \
	apt-get update && \
	apt-get install -y migrate

RUN go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest && \
	go install github.com/google/wire/cmd/wire@latest

WORKDIR /home/app

RUN git config --global --add safe.directory /home/app

COPY . .
RUN go mod tidy

CMD ["tail", "-f", "/dev/null"]
