apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-ms-auth
spec:
  selector:
    app: rabbitmq-ms-auth
  ports:
    - port: 5672
      name: app
      protocol: TCP
    - port: 15672
      name: dashboard
      protocol: TCP
  clusterIP: None
