###
POST http://localhost:8080/auth/signup
content-Type: 'application/json'

{
  "name": "lorem",
  "email": "lorem@ipsum.com",
  "password": "P@ssw0rd"
}

###
POST http://localhost:8080/auth/signin
content-Type: 'application/json'

{
  "email": "lorem@ipsum.com",
  "password": "P@ssw0rd"
}

###
POST http://localhost:8080/auth/forgot-password
content-Type: 'application/json'

{
  "email": "LOREM@ipsum.com"
}

###
POST http://localhost:8080/auth/update-password
content-Type: 'application/json'
x_access_token: Bearer {TOKEN_HERE}

{
  "password": "P@ssw0rd"
}

###
POST http://localhost:8080/auth/confirm-email
content-Type: 'application/json'
x_access_token: Bearer {TOKEN_HERE}