apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-auth
spec:
  selector:
    matchLabels:
      app: ms-auth
  template:
    metadata:
      labels:
        app: ms-auth
    spec:
      containers:
      - name: ms-auth
        image: marcoscoutinhodev/ms-auth:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: ms-auth
        - configMapRef:
            name: ms-auth
