// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package postgres

import (
	"database/sql"
)

type User struct {
	ID             string
	Name           string
	Email          string
	Password       string
	ConfirmedEmail sql.NullBool
}
